print("Tämä ohjelma laskee antamiesi 3 luvun keskiarvon.")
luku1 = int(input("Anna luku 0 ja 10 väliltä: "))
luku2 = int(input("Anna toinen luku 0 ja 10 väliltä: "))
luku3 = int(input("Anna kolmas luku 0 ja 10 väliltä: "))
keskiarvo = (luku1+luku2+luku3)/3
print(f'\nAntamiesi lukujen summa on {luku1+luku2+luku3}.')
print(f'Antamiesi lukujen keskiarvo on {keskiarvo}.')
print(f'Keskiarvo on kokonaislukuna {int(keskiarvo)}.')
print(f'Keskiarvo pyöristettynä 3 desimaalin tarkkuuteen on {round(keskiarvo, 3)}.')
print("Kiitos ohjelman käytöstä.")